name: Security

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "17 3 * * 1"   # weekly Monday 03:17 UTC

permissions:
  contents: read
  security-events: write

jobs:
  # Optional: CodeQL (can remove if you don't use GHAS/private repos)
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python
      - uses: github/codeql-action/analyze@v3

  # Bandit in advisory mode; excludes tests/ and uploads SARIF if produced
  bandit_advisory:
    name: Bandit (advisory -> SARIF, exclude tests/)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      # SARIF support requires the 'sarif' extra
      - run: pip install "bandit[toml,sarif]>=1.7.9"
      - name: Run Bandit -> SARIF (do not fail PR)
        run: |
          bandit -r . \
            --severity-level low \
            --confidence-level low \
            -x tests,.venv,venv,build,dist,.git,__pycache__ \
            -f sarif -o bandit.sarif || true
      - name: Upload SARIF to code scanning
        if: hashFiles('bandit.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif

  # Optional: dependency vuln scan (pip-audit)
  pip-audit:
    name: pip-audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt || true
      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
